version: "3"
services:
  signal-cli-rest-api:
    image: bbernhard/signal-cli-rest-api:latest
    environment:
      - MODE=json-rpc
      - JSON_RPC_IGNORE_ATTACHMENTS=true
      - JSON_RPC_IGNORE_STORIES=true
      - JSON_RPC_IGNORE_AVATARS=true
      - JSON_RPC_IGNORE_STICKERS=true 
    ports:
      - "8080:8080"
    volumes:
      - "signal-cli-data:/home/.local/share/signal-cli" # the folder contains the password and cryptographic keys when a new number is registered
    restart: unless-stopped
      
  fs-bot:
    image: jiemakel/fs-bot:latest
    environment:
      SIGNAL_SERVICE: signal-cli-rest-api:8080
      PHONE_NUMBER: ${PHONE_NUMBER}
      SIGNAL_GROUP_ID: ${SIGNAL_GROUP_ID}

      ADMIN_1_PHONE: ${ADMIN_1_PHONE}
      ADMIN_2_PHONE: ${ADMIN_2_PHONE}

      CHILD_1_PHONE: ${CHILD_1_PHONE}
      CHILD_1_MS_ID: ${CHILD_1_MS_ID}
      CHILD_1_NAME: ${CHILD_1_NAME}
      CHILD_2_PHONE: ${CHILD_2_PHONE}
      CHILD_2_MS_ID: ${CHILD_2_MS_ID}
      CHILD_2_NAME: ${CHILD_2_NAME}

      MS_FAMILY_EMAIL: ${MS_FAMILY_EMAIL}

      TZ: ${TZ}
      DATA_DIR: ${DATA_DIR}
      BOT_LANGUAGE: ${BOT_LANGUAGE}
    depends_on:
      - signal-cli-rest-api
    volumes:
      - fs-bot-data:/app/data
    restart: unless-stopped    
    
volumes:
  signal-cli-data:
  fs-bot-data:
